# Setup

In [1]:
import numpy as np
import sklearn
import pandas as pd
import os
import zipfile

In [19]:
os.path.abspath('.')

'C:\\Users\\Mike\\DataScienceProjects\\datahack2020\\datahack2020\\analyses\\team04\\mg'

In [20]:
# Set up some directory info, and figure export path
PROJECT_ROOT_DIR = '../../../'
NOTEBOOK_ID = 'EDA_mg'
FIGURE_EXPORT_PATH = os.path.join(PROJECT_ROOT_DIR, "analyses/team04/mg/figures", NOTEBOOK_ID)
os.makedirs(FIGURE_EXPORT_PATH, exist_ok = True)

In [21]:
# Define figure export
def save_fig(fig_id, tight_layout=True, fig_extension = "png", resolution = 300):
    path = os.path.join(FIGURE_EXPORT_PATH, fig_id + '.' + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format = fig_extension, dpi = resolution)

In [22]:
# Set up some plotting conveniences/settings
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [24]:
# Investigate Files
DATA_PATH = os.path.join(PROJECT_ROOT_DIR, "data/data.zip")
data = zipfile.ZipFile(DATA_PATH)    
# List all data files:
data.namelist()

['data/',
 'data/hf_samsha_providers.csv',
 'data/pp_refill_events.csv',
 'data/pp_sep_site_exchanges.csv',
 'data/dph_od_resident_counts.csv',
 'data/.DS_Store',
 'data/hf_physician_locator.csv',
 'data/dph_dash_ems_naloxone_zip.csv',
 'data/pp_refill_zipcode_metrics.csv',
 'data/dph_dash_n_ed_transfers.csv',
 'data/dph_dash_ems_naloxone_sex.csv',
 'data/pp_sep_site_participants.csv',
 'data/dph_dash_n_naloxone_admins.csv',
 'data/dph_od_incident_counts.csv',
 'data/dph_dash_ems_naloxone_age.csv',
 'data/hf_samsha_programs.csv']

In [47]:
# load data
hf_samsha_providers = pd.read_csv(data.open(r'data/hf_samsha_providers.csv', pwd = b"*$1Y5.2,|sG$"))
pp_refill_events = pd.read_csv(data.open(r'data/pp_refill_events.csv', pwd = b'*$1Y5.2,|sG$'))
pp_sep_site_exchanges = pd.read_csv(data.open(r'data/pp_sep_site_exchanges.csv', pwd = b'*$1Y5.2,|sG$'))
dph_od_resident_counts = pd.read_csv(data.open(r'data/dph_od_resident_counts.csv', pwd = b'*$1Y5.2,|sG$'))
pp_refill_zipcode_metrics = pd.read_csv(data.open(r'data/pp_refill_zipcode_metrics.csv', pwd = b'*$1Y5.2,|sG$'))
pp_sep_site_participants = pd.read_csv(data.open(r'data/pp_sep_site_participants.csv', pwd = b'*$1Y5.2,|sG$'))
hf_physician_locator = pd.read_csv(data.open(r'data/hf_physician_locator.csv', pwd = b'*$1Y5.2,|sG$'))

In [48]:
pp_refill_events.head(5)

,age,gender,race,n_pp_refill,n_o_refill,n_ods,n_admins,n_revivals,used_narcan_type,ml_naloxone,...,od_drug_cocaine,od_drug_fentanyl,od_drug_unknown,od_drug_other,od_present,od_present_breath,od_present_unresponsive,od_present_coloring,od_present_other,data_date_range
0,42.0,m,white,1.0,0.0,5.0,6.0,6.0,nose,NaN,...,0.0,1.0,0.0,0.0,bbp,0.0,0.0,1.0,0.0,2018-q1-q2
1,33.0,m,white,8.0,0.0,2.0,1.0,1.0,injectable,NaN,...,0.0,1.0,0.0,0.0,all of the above,1.0,1.0,1.0,0.0,2018-q1-q2
2,32.0,m,white,2.0,1.0,NaN,NaN,NaN,nose,NaN,...,0.0,0.0,0.0,0.0,bbp,0.0,0.0,1.0,0.0,2018-q1-q2
3,36.0,m,white,1.0,0.0,10.0,1.0,1.0,nose,NaN,...,0.0,0.0,0.0,1.0,uou,0.0,1.0,0.0,0.0,2018-q1-q2
4,38.0,f,white,2.0,0.0,10.0,0.0,0.0,nose,0.0,...,0.0,1.0,0.0,0.0,"pcnb, uou",1.0,1.0,0.0,0.0,2018-q1-q2

In [50]:
pp_sep_site_exchanges.head(5)

,site_id,visit_month,syringes_returned,syringes_dispensed,no_exchanging_for
0,1.0,2019-01-01,5625,6175,48
1,1.0,2019-02-01,12700,13960,89
2,1.0,2019-03-01,8862,10470,76
3,1.0,2019-04-01,6130,7070,64
4,1.0,2019-05-01,9369,9830,66

In [51]:
pp_refill_zipcode_metrics.head(5)

,participant_zip,avg_outcome_ems,avg_outcome_police,avg_outcome_ed,avg_outcome_death,avg_outcome_unk,avg_outcome_ok,avg_od_drug_heroin,avg_od_drug_cocaine,avg_od_drug_fentanyl,avg_od_drug_unknown,avg_od_drug_other,avg_od_present_breath,avg_od_present_unresponsive,avg_od_present_coloring,avg_od_present_other,avg_cpr_used,n_observations
0,19111.0,0.366667,0.150000,0.200000,0.000000,0.150000,0.700000,0.517241,0.068966,0.310345,0.241379,0.161290,0.642857,0.750000,0.678571,0.000000,0.600000,31
1,19120.0,0.318182,0.210526,0.052632,0.000000,0.052632,0.526316,0.695652,0.130435,0.652174,0.000000,0.000000,0.304348,0.565217,0.478261,0.043478,0.428571,26
2,19122.0,0.187500,0.115385,0.000000,0.000000,0.076923,0.769231,0.366667,0.033333,0.366667,0.266667,0.093750,0.387097,0.419355,0.322581,0.225806,0.333333,36
3,19124.0,0.358209,0.176471,0.125000,0.026144,0.071895,0.581699,0.820513,0.200000,0.528205,0.061538,0.088235,0.438144,0.541237,0.556701,0.030928,0.453333,219
4,19125.0,0.206186,0.115942,0.072464,0.043478,0.202899,0.608696,0.648352,0.109890,0.494505,0.098901,0.140000,0.377778,0.511111,0.555556,0.011236,0.419355,102

In [52]:
pp_sep_site_participants.head(5)

   site_id visit_month  count_distinct_participants
0        1  2019-01-01                           42
1        1  2019-10-01                           51
2        1  2019-11-01                           73
3        1  2019-12-01                           54
4        1  2019-02-01                           74